name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_KEY }} > gcloud-auth.json
          gcloud auth activate-service-account --key-file=gcloud-auth.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # Set default region for gcloud (optional)
      - name: Set gcloud default region
        run: |
          gcloud config set run/region us-central1

      # Install Node.js (if necessary) and dependencies
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Build and deploy to Cloud Run using Cloud Build
      - name: Build and Deploy
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
          gcloud run deploy ${{ env.SERVICE_NAME }} --image gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA --platform managed --allow-unauthenticated
