name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      # Run Cloud Build using cloudbuild.yaml
      - name: Run Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml --substitutions=_COMMIT_SHA=$(git rev-parse --short HEAD)

      # Output deployment status
      - name: Show deployment status
        run: |
          echo "Deployment to Cloud Run completed successfully!"
