name: Build and Deploy a nodeApp to Cloud Run using GCR

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-NodeApp

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install a specific version of the gcloud SDK
    - name: Install gcloud SDK
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-290.0.1-linux-x86_64.tar.gz
        tar zxvf google-cloud-sdk-290.0.1-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh -q

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    # Initialize the gcloud SDK
    - name: Initialize gcloud
      run: |
        ./google-cloud-sdk/bin/gcloud init --skip-diagnostics

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        ./google-cloud-sdk/bin/gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        ./google-cloud-sdk/bin/gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
